### ISSUE TITLE
about using this method on complete and partial point cloud

### ISSUE THREAD

**Issue by wra1229** [clinplayer/Point2Skeleton#22]
Hello,

can your method extract the skeleton of partial point cloud? something like a human face with non-closed surface.

Best.

**Comment by clinplayer** [comment]
Hi. What do you mean by "partial point cloud" - closed shapes having missing parts, or non-closed surfaces that is a 2D manifold? The method can be applied for shape with missing parts, while since we use convex combination to generate the skeletal points, the convex hull of the partial shape should be roughly consistent with the original shape. But for 2D manifold like a human face, the definition of its skeleton is essentially different from 3D closed shapes, so this method is not applicable.

**Comment by wra1229** [comment]
Thanks a lot！I get it!
